=== yuliyafedartsova/issuetracker_yuliya_fedartsova/src/main/java/org/training/issuetracker/xml/issues.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="issues">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="issue" type="Issue"  minOccurs="1" maxOccurs="unbounded" /> 
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:complexType name="Issue">
	<xs:sequence> 
		<xs:element name="id" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		<xs:element name="priority" type="xs:integer" minOccurs="1" maxOccurs="1" />
		<xs:element name="assignee" type="xs:integer" minOccurs="0" maxOccurs="1"/>
		<xs:element name="type" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		<xs:element name="summary" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="status" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		<xs:element name="project" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		<xs:element name="resolution" type="xs:integer" minOccurs="0" maxOccurs="1"/>
		<xs:element name="found" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		<xs:element name="createDate" type="xs:date" minOccurs="1" maxOccurs="1"/>
		<xs:element name="author" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		<xs:element name="modifyDate" type="xs:date" minOccurs="0" maxOccurs="1"/>
		<xs:element name="modifier" type="xs:integer" minOccurs="0" maxOccurs="1"/>
	</xs:sequence> 
</xs:complexType>
</xs:schema>

=== yuliyafedartsova/issuetracker_yuliya_fedartsova/src/main/webapp/files/issues.xml
<?xml version="1.0" encoding="UTF-8"?>
<issues xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="issues.xsd">
  <issue>
		<id> 1 </id>
		<priority> 3 </priority>
		<assignee> 1 </assignee>
		<type> 0 </type>
		<summary> Poor error handling when attaching multiple files and at least one upload fails </summary>
		<description> When one of the files fails to upload, an error message is displayed, requiring the user to hit the back button. In fact, the other files are uploaded successfully. This behavior is confusing to users, and furthermore if you do the same thing when reporting a new issue and then resubmit, you get duplicate issues </description>
	    <status> 2 </status>
		<project> 0 </project>
		<found> 0 </found>
		<createDate> 2013-10-02 </createDate>
		<author> 2 </author>
		<modifyDate> 2013-10-04 </modifyDate>
		<modifier> 0 </modifier>
	</issue>
	<issue>
		<id> 2 </id>
		<priority> 3 </priority>
		<assignee> 4 </assignee>
		<type> 2 </type>
		<summary> The state changed automaticly after assign to somebody </summary>
		<description> The issue state change to anther one after I assign to someone, but I want it keep the 'New' </description>
	    <status> 2 </status>
		<project> 1 </project>
		<found> 5 </found>
		<createDate> 2013-10-03 </createDate>
		<author> 3 </author>
		<modifyDate> 2013-10-07 </modifyDate>
		<modifier> 2 </modifier>
	</issue>
	<issue>
		<id> 3 </id>
		<priority> 2 </priority>
		<assignee> 2 </assignee>
		<type> 3 </type>
		<summary> Sort of custom fields does not use data type </summary>
		<description> I added a custom field to view_all_bug_page.php using custom_function_inc.php. The field is a "number" field (long integer) but is stored internally as string in mantis/mysql. If I click on the column header of this custom field the view gets sorted alphabetically (not numerically). </description>
	    <status> 1 </status>
		<project> 2 </project>
		<found> 6 </found>
		<createDate> 2013-10-05 </createDate>
		<author> 7 </author>
	</issue>
	<issue>
		<id> 4 </id>
		<priority> 0 </priority>
		<type> 1 </type>
		<summary> Page goes blank </summary>
		<description> Page goes blank for the action like- Edit, Update, Change Status, etc. Works fine on local machine, but not working on Server </description>
	    <status> 0 </status>
		<project> 3 </project>
		<found> 11 </found>
		<createDate> 2013-10-07 </createDate>
		<author> 6 </author>
	</issue>
	<issue>
		<id> 5 </id>
		<priority> 3 </priority>
		<type> 1 </type>
		<summary> Numeric Custom fields on View All don't sort correctly </summary>
		<description> When the custom field is selected to sort on, it sorts by a character order, not numeric values, so 2 will sort before 10. </description>
	    <status> 0 </status>
		<project> 3 </project>
		<found> 7  </found>
		<createDate> 2013-10-08 </createDate>
		<author> 7 </author>
	</issue>
	<issue>
		<id> 6 </id>
		<priority> 2 </priority>
		<assignee> 2 </assignee>
		<type> 1 </type>
		<summary> When viewing bugs from a search, only current page of results is navigable </summary>
		<description> When an issue has been visited from the "View Issues" page, a set of navigation links appears at the top of the issue, allowing you to navigate through the resultset. </description>
	    <status> 1 </status>
		<project> 2 </project>
		<found> 10  </found>
		<createDate> 2013-10-09 </createDate>
		<author> 0 </author>
	</issue>
	<issue>
		<id> 7 </id>
		<priority> 2 </priority>
		<type> 1 </type>
		<summary> Cookie problem on logout </summary>
		<description> If I log out of mantis I receive a system warning (header already modified) and I cannot login again. I always only get "Access Denied". This behavior stops if I delete all mantis cookies. This is reproducible on my installation as well as on this mantis installation. </description>
	    <status> 0 </status>
		<project> 1 </project>
		<found> 5  </found>
		<createDate> 2013-10-11 </createDate>
		<author> 3 </author>
		<modifyDate> 2013-10-13 </modifyDate>
		<modifier> 5 </modifier>
	</issue>
	<issue>
		<id> 8 </id>
		<priority> 1 </priority>
		<assignee> 1 </assignee>
		<type> 1 </type>
		<summary> Email notification is set to all developers even if bug is assigned at the moment of addition </summary>
		<description> When adding a bug and selecting developer in "assign to" dropdown, notification is sent to all developers again. I think it's more correct to use "assign" rules, but not "new". </description>
	    <status> 2 </status>
		<project> 0 </project>
		<found> 4  </found>
		<createDate> 2013-10-14 </createDate>
		<author> 4 </author>
	</issue>
	<issue>
		<id> 9 </id>
		<priority> 1 </priority>
		<assignee> 2 </assignee>
		<type> 1 </type>
		<summary> Clicking on Project Name in view_all_bugs has unexpected results </summary>
		<description> If you select "All Projects" in the view_all_bugs page, you are presented with a list of bugs. There are link in the category column that I would think would filter by the project name. Clicking the link is inconsistent, either sorting ascending or descending by the project name. The almost never end up with the project you click in the first page of the list. </description>
	    <status> 1 </status>
		<project> 2 </project>
		<found> 10  </found>
		<createDate> 2013-10-15 </createDate>
		<author> 4 </author>
	</issue>
</issues>
