=== yuliyafedartsova/issuetracker_yuliya_fedartsova/src/main/java/org/training/issuetracker/xml/projects.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="projects">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="project" type="Project"  minOccurs="1" maxOccurs="unbounded" /> 
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:complexType name="Project">
	<xs:sequence> 
		<xs:element name="id" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
		<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"/>
		<xs:element name="manager" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		<xs:element name="build" type="xs:integer" minOccurs="1" maxOccurs="1"/>
	</xs:sequence> 
</xs:complexType>
</xs:schema>

=== yuliyafedartsova/issuetracker_yuliya_fedartsova/src/main/webapp/files/projects.xml
<?xml version="1.0" encoding="UTF-8"?>
<projects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projects.xsd">
  <project> 
	    <id> 1 </id>
	    <name> Bugzilla </name>
	    <description> Bugzilla is server software designed to help you manage software development. </description>
	    <manager> 1 </manager>
	    <build> 8 </build>
	</project>
	<project> 
		<id> 2 </id>
	    <name> Mantis Bug Tracker </name>
	    <description> MantisBT is a free popular web-based bugtracking system (feature list). It is written in the PHP scripting language and works with MySQL, MS SQL, and PostgreSQL databases and a webserver. MantisBT has been installed on Windows, Linux, Mac OS, OS/2, and others. </description>
	    <manager> 2 </manager>
	    <build> 9 </build>
	</project>
	<project> 
		<id> 3 </id>
	    <name> Trac </name>
	    <description> Trac is an enhanced wiki and issue tracking system for software development projects. Trac uses a minimalistic approach to web-based software project management. </description>
	    <manager> 3 </manager>
	    <build> 10 </build>
	 </project>
	<project> 
		<id> 4 </id>
	    <name> Redmine </name>
	    <description> Redmine is a flexible project management web application. Written using the Ruby on Rails framework, it is cross-platform and cross-database. Redmine is open source and released under the terms of the GNU General Public License v2 (GPL). </description>
	    <manager> 4 </manager>
	    <build> 11 </build>
	</project>
</projects>
