=== yuliyafedartsova/issuetracker_yuliya_fedartsova/src/main/java/org/training/issuetracker/xml/versions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="versions">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="version" type="Version"  minOccurs="1" maxOccurs="unbounded" /> 
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:complexType name="Version">
	<xs:sequence> 
		<xs:element name="id" type="xs:integer" minOccurs="1" maxOccurs="1"/>
		<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
		<xs:element name="project" type="xs:integer" minOccurs="1" maxOccurs="1"/>
	</xs:sequence> 
</xs:complexType>
</xs:schema>

=== yuliyafedartsova/issuetracker_yuliya_fedartsova/src/main/webapp/files/versions.xml
<?xml version="1.0" encoding="UTF-8"?>
<versions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="versions.xsd">
  <version> 
	    <id> 1 </id>
	    <name> 1.0.0.0 beta </name>
	    <project> 1 </project>
	</version>
	<version> 
		<id> 2 </id>
	    <name> 1.0.0.0 beta  </name>
	    <project> 2 </project>
	</version>
	<version> 
		<id> 3 </id>
	    <name> 1.0.0.0 beta </name>
	    <project> 3 </project>
	</version>
	<version> 
		<id> 4 </id>
	    <name> 1.0.0.0 beta </name>
	    <project> 4 </project>
	</version>
	<version> 
		<id> 5 </id>
	    <name> 1.0.0.1 beta </name>
	    <project> 1 </project>
	</version>
	<version> 
		<id> 6 </id>
	    <name> 1.0.0.1 beta  </name>
	    <project> 2 </project>
	</version>
	<version> 
		<id> 7 </id>
	    <name> 1.0.0.1 beta </name>
	    <project> 3 </project>
	</version>
	<version> 
		<id> 8 </id>
	    <name> 1.0.0.1 beta </name>
	    <project> 4 </project>
	</version>
	<version> 
		<id> 9 </id>
	    <name> 1.0.0.2 </name>
	    <project> 1 </project>
	</version>
	<version> 
		<id> 10 </id>
	    <name> 1.0.0.2  </name>
	    <project> 2 </project>
	</version>
	<version> 
		<id> 11 </id>
	    <name> 1.0.0.2  </name>
	    <project> 3 </project>
	</version>
	<version> 
		<id> 12 </id>
	    <name> 1.0.0.2  </name>
	    <project> 4 </project>
	</version>
</versions>
